framework:
    messenger:
        routing:
            # We want the command below to be handled async with the "messenger.default_sender" (AMQP producer).
            'App\Message\Command\CreateNumber': messenger.sender.default

        adapters:
            default: "%env(AMQP_DSN)%"
