framework:
    messenger:
        transports:
            default: '%env(AMQP_DSN)%'

        default_bus: messenger.bus.command
        buses:
            messenger.bus.command:
                middleware:
                    - validation
                    - doctrine_transaction

            messenger.bus.event:
                default_middleware: allow_no_handlers
                middleware:
                    - validation

            messenger.bus.query:
                middleware:
                    - validation

        routing:
            # We want the command below to be handled async with the "messenger.default_sender" (AMQP producer).
            'App\Message\Command\CreateNumber': default